export const prophetsData = [
  {
    name: "Hosea",
    mainSin: "Infidelity, turning to idols rather than God (ch. 1-3)",
    judgment: "Exile and removal of blessings, but not complete doom (9:3–6)",
    mercy: "Restoration imagery: Following repentance, God mends and rebuilds relationships (14:1-4)",
    character: "Even being deceived, God remains patient, loving, and faithful (11:1-4)",
    responsibility: "People must turn back to God in a real manner, not merely on the outside (6:1–3)",
    theme: "God's covenant love and faithfulness despite Israel's unfaithfulness",
    purpose: "To illustrate God's persistent love and the consequences of spiritual adultery",
    toWhom: "The Northern Kingdom of Israel",
    specialMessage: "Restoration and healing come through repentance and return to God",
    writingDate: "Around 750 BC",
    location: "Northern Kingdom"
  },
  {
    name: "Amos",
    mainSin: "Community injustice, such as mistreating poor people while upholding religious customs (5:11–12)",
    judgment: "Religious deeds will not escape the inevitable judgment (5:18–20)",
    mercy: "A brief message of hope: God keeps the last days alive (9:11–15)",
    character: "God rejects meaningless worship because he is just and righteous (5:24)",
    responsibility: "People must genuinely seek God, act justly, and pursue goodness (5:14–15)",
    theme: "Social justice and righteousness",
    purpose: "To condemn oppression and injustice in Israel",
    toWhom: "The people of Israel, particularly the wealthy and powerful",
    specialMessage: "True worship requires justice and righteousness, not just rituals",
    writingDate: "Around 760 BC",
    location: "Southern Kingdom"
  },
  {
    name: "Joel",
    mainSin: "Spiritual carelessness and failure to seek God (1:2–4)",
    judgment: "Natural disasters serve as a picture for judgment and 'the Day of the Lord' (2:1–11)",
    mercy: "Following repentance, God promises restoration and the outpouring of His Spirit (2:12–13, 28–29)",
    character: "God is merciful, kind, and patient (2:13)",
    responsibility: "Repentance requires sincere hearts, not just procedures (2:12)",
    theme: "The Day of the Lord and restoration",
    purpose: "To call Judah to repentance in the face of impending judgment",
    toWhom: "The people of Judah",
    specialMessage: "Repentance leads to restoration and the outpouring of God's Spirit",
    writingDate: "Around 835 BC",
    location: "Judah"
  },
  {
    name: "Obadiah",
    mainSin: "Acts of aggression against a brother nation and national pride (vv. 3–4, 10)",
    judgment: "Edom is proclaimed to be completely destroyed and humiliated (vv. 15–16)",
    mercy: "God's justice implies mercy, but it isn't made clear to Edom",
    character: "According to verse 15, God is the ultimate judge of all nations",
    responsibility: "Nations are responsible for their treatment of other people (v. 10)",
    theme: "Judgment on Edom and God's sovereignty",
    purpose: "To prophesy against Edom's pride and hostility toward Judah",
    toWhom: "The nation of Edom",
    specialMessage: "Pride and aggression against God's people will be judged",
    writingDate: "Around 586 BC",
    location: "Edom"
  },
  {
    name: "Jonah",
    mainSin: "Disobedience and lack of compassion, especially from God's messenger (1:1–3; 4:1–2)",
    judgment: "God's authority over nature and the impact of disobedience serve as examples of judgment (1:4–17)",
    mercy: "God is merciful to sinners who turn from their sins, including rivals (3:10)",
    character: "Even in the face of adversaries, God is kind and compassionate (4:2)",
    responsibility: "God's followers are required to share His mercy and respond to His summons (1:3; 4:11)",
    theme: "God's mercy and compassion",
    purpose: "To demonstrate God's universal love and willingness to forgive",
    toWhom: "The people of Nineveh (Assyrians)",
    specialMessage: "God's mercy extends to all nations who repent",
    writingDate: "Around 780 BC",
    location: "Nineveh"
  },
  {
    name: "Nahum",
    mainSin: "The brutality, aggression, and power of a strong kingdom (3:1–4)",
    judgment: "Nineveh will undoubtedly face judgement and total devastation (1:8; 3:19)",
    mercy: "God is a place of refuge for those who trust Him (1:7)",
    character: "God is strong, just, and does not submit to wickedness (1:2-3)",
    responsibility: "Rather of being afraid of wicked forces, people are exhorted to trust God's justice (1:7)",
    theme: "God's judgment on wickedness and comfort for the faithful",
    purpose: "To assure Judah of Nineveh's impending destruction",
    toWhom: "The people of Judah",
    specialMessage: "God is a refuge for those who trust Him and judge of the wicked",
    writingDate: "Around 650 BC",
    location: "Nineveh"
  },
  {
    name: "Micah",
    mainSin: "Social injustice and corruption in leadership with specific attention to those who are poor and oppressed (2:1-2; 3:1-3)",
    judgment: "Jerusalem is to be destroyed due to its wickedness (3:12)",
    mercy: "Hope for a future peace and the ability to restore Israel under God's leadership (4:1-4)",
    character: "God wants us to be righteous and gives us justice, mercy, and loyalty (6:8)",
    responsibility: "The Lord requires people to do what is just, love mercy, and act justly (6:8)",
    theme: "Social justice, judgment, and restoration",
    purpose: "To condemn social injustice and idolatry while promising restoration",
    toWhom: "The people of Judah and Israel",
    specialMessage: "True religion involves justice, mercy, and humility before God",
    writingDate: "Around 735 BC",
    location: "Judah"
  },
  {
    name: "Habakkuk",
    mainSin: "Violence and injustice versus why should God permit evil during this time period of hardship (1:2-4)",
    judgment: "God warns that Babylon will destroy the Israelites but this is uncomfortable for the prophet (1:6)",
    mercy: "Faith and trust in God can help to provide a sense of hope and comfort during times of trial or pain (2:4)",
    character: "God has all authority over creation and does not act unjustly, even if His actions are difficult to understand (2:20)",
    responsibility: "The Lord encourages us to live in a state of faith, rather than of fear (2:4)",
    theme: "Faith in God's sovereignty amid injustice",
    purpose: "To address the problem of evil and encourage faith in God's justice",
    toWhom: "The people of Judah",
    specialMessage: "The righteous live by faith, trusting God's ultimate justice",
    writingDate: "Around 608 BC",
    location: "Judah"
  },
  {
    name: "Zephaniah",
    mainSin: "Idolatry, pride, and immoral behavior existing in Judah (1:4-6)",
    judgment: "Judgment is described as 'The Day of the Lord' and will be incredibly horrific (1:14-18)",
    mercy: "The Lord has promised to bring about restoration to His faithful remnant (3:9–13)",
    character: "God is completely holy and powerful; He will show mercy to those who are humbled (3:17)",
    responsibility: "We need to have a desire for humility and to live righteously (2:3)",
    theme: "The Day of the Lord and purification",
    purpose: "To warn of coming judgment and call for repentance",
    toWhom: "The people of Judah",
    specialMessage: "God will purify and restore the humble remnant",
    writingDate: "Around 640 BC",
    location: "Judah"
  },
  {
    name: "Haggai",
    mainSin: "Spiritual neglect/ misplaced priorities– people are more concerned with their own lives than spending time in/ around God's house (1:4)",
    judgment: "There is a warning from God regarding disobedience causing a lack of blessing (1:9-11)",
    mercy: "The Lord has promised renewed blessings when His people obey Him (2:18–19)",
    character: "God displays His faithfulness and responds to His people by giving them confidence through His work (1:13)",
    responsibility: "The Lord commands His People to put God first, obey God's commandments (1:8)",
    theme: "Rebuilding the temple and God's presence",
    purpose: "To motivate the returned exiles to rebuild God's temple",
    toWhom: "The returned exiles in Judah",
    specialMessage: "God's presence in the temple brings blessing and glory",
    writingDate: "Around 520 BC",
    location: "Judah"
  },
  {
    name: "Zechariah",
    mainSin: "Spiritual apathy and hypocrisy, particularly by those in leadership positions (7:4-6)",
    judgment: "Discipline and refining will result in judgement, but will not result in complete destruction (13:8-9)",
    mercy: "Messianic hope is expressed through the prophetic promise that God will restore His people and dwell among His people (8:3; 9:9)",
    character: "God's patience, faithfulness, and desire to redeem the entire world means He has a purpose for history (4:10)",
    responsibility: "We are called to return unto the Lord and live with Faithfulness (1:3)",
    theme: "Restoration, cleansing, and Messiah",
    purpose: "To encourage the rebuilding of Jerusalem and temple, and announce future restoration",
    toWhom: "The returned exiles in Judah",
    specialMessage: "God promises complete restoration through the coming Messiah",
    writingDate: "Around 520 BC",
    location: "Judah"
  },
  {
    name: "Malachi",
    mainSin: "Religious indifference (dishonoring God through carelessness in worship) (1:6-8)",
    judgment: "God will judge the unfaithful and unjust (3:5)",
    mercy: "A messenger will be sent to heal those who believe (3:1, 4:2)",
    character: "God's unchanging nature and faithfulness requires that we give Him honor and obey Him (3:6)",
    responsibility: "The Lord calls upon His People to Worship Him, Obey Him and Commit to Him (3:7)",
    theme: "Covenant faithfulness and coming judgment",
    purpose: "To confront spiritual apathy and call for covenant renewal",
    toWhom: "The post-exilic community in Judah",
    specialMessage: "God will send a messenger to prepare the way for His coming",
    writingDate: "Around 430 BC",
    location: "Judah"
  }
];

export const chartsData = {
  writingDates: [
    { prophet: "Joel", date: 835, location: "Judah" },
    { prophet: "Jonah", date: 780, location: "Nineveh" },
    { prophet: "Amos", date: 760, location: "Southern Kingdom" },
    { prophet: "Hosea", date: 750, location: "Northern Kingdom" },
    { prophet: "Micah", date: 735, location: "Judah" },
    { prophet: "Nahum", date: 650, location: "Nineveh" },
    { prophet: "Zephaniah", date: 640, location: "Judah" },
    { prophet: "Habakkuk", date: 608, location: "Judah" },
    { prophet: "Obadiah", date: 586, location: "Edom" },
    { prophet: "Haggai", date: 520, location: "Judah" },
    { prophet: "Zechariah", date: 520, location: "Judah" },
    { prophet: "Malachi", date: 430, location: "Judah" }
  ],
  interconnections: {
    judgment: ["All prophets warn of coming judgment"],
    mercy: ["Hope and restoration for the repentant"],
    geography: ["Israel, Judah, and surrounding nations"],
    history: ["Assyrian and Babylonian periods"]
  },
  sixProphets: [
    { name: "Hosea", theme: "Covenant love and infidelity" },
    { name: "Amos", theme: "Social justice and righteousness" },
    { name: "Joel", theme: "Day of the Lord and restoration" },
    { name: "Obadiah", theme: "Judgment on Edom" },
    { name: "Jonah", theme: "God's mercy and compassion" },
    { name: "Nahum", theme: "Judgment on wickedness" }
  ]
};
